public enum enumErrorCode
{
	RUN_SUCCESS = 1,
	RUNERR_NOSUPPORT = 0,
	RUNERR_UNKNOWNERROR = -1,
	RUNERR_NO_OPEN_COMM = -2,
	RUNERR_WRITE_FAIL = -3,
	RUNERR_READ_FAIL = -4,
	RUNERR_INVALID_PARAM = -5,
	RUNERR_NON_CARRYOUT = -6,
	RUNERR_DATAARRAY_END = -7,
	RUNERR_DATAARRAY_NONE = -8,
	RUNERR_MEMORY = -9,
	RUNERR_MIS_PASSWORD = -10,
	RUNERR_MEMORYOVER = -11,
	RUNERR_DATADOUBLE = -12,
	RUNERR_MANAGEROVER = -14,
	RUNERR_FPDATAVERSION = -15
}
